### PR TITLE
SRI: Changing rel value to keyword for matching stylesheets

### PR DESCRIPTION
**Pull request by jonathanKingston**
As rel can contain multiple values using the word keyword would allow for different attributes here.

### CODE REVIEW

**Comment by mozfreddyb** [comment]
This is something that needs to be addressed in implementations, if they match `relValue == "stylesheet"`.
@fmarier said he's already doing the right thing. @metromoxie, can you take a look?

**Comment by fmarier** [comment]
lgtm

**Comment by fmarier** [comment]
We should also find a way to test it in the web platform tests. /cc @hillbrad

**Comment by metromoxie** [comment]
I'll check tomorrow.

**Comment by metromoxie** [comment]
It appears that Chrome is behaving correctly here. I'll update the web platform tests shortly with some tests for this.

**Comment by jonathanKingston** [comment]
:+1: thanks @metromoxie, @fmarier and @mozfreddyb for looking into this.

**Pull request merged**
