### PR TITLE
Explore automatic publication with Travis & Echidna

### PR DESCRIPTION
**Pull request by tripu**
This is an incomplete attempt to get WDs here to be automatically published using [Echidna](https://github.com/w3c/echidna/wiki). There are a few issues to get this done right now.

**Changes:**
* Added Echidna manifest files for three of the specs here (as samples or templates): [content security policy](https://w3c.github.io/webappsec/specs/content-security-policy/), [credential management level 1](https://w3c.github.io/webappsec/specs/credentialmanagement/) and [mixed content](https://w3c.github.io/webappsec/specs/mixedcontent/).
* Added some lines to Travis config file, trying to illustrate how the *content security policy* WD could be set up with Travis/Echidna; there is necessary data missing.

**What's missing:**

* Collect all the URLs of the group's decisions to publish each spec, and set them up with Travis/Echidna.
* [Get a token](https://github.com/w3c/echidna/wiki/Token-creation) for each spec.
* Encrypt the tokens with Travis and set the resulting strings up with Travis/Echidna ([instructions](https://github.com/w3c/echidna/wiki/Setting-up-Echidna-as-a-GitHub-hook)).
* For WDs that are made up of more files than the index HTML, list all those files in additional lines in their manifests.

**Notes:**
* As it is now, Travis would publish *all* WDs every time there's a commit/tag/branch. Some ideas to solve that, off the top of my head:
  * Split this repo in several repos; one per spec, like other WGs do (recommended).
  * Write a custom script that would invoke Echidna to publish only the right spec (the one where there has been a commit etc), and use that in the `script` section of the Travis config file.
* Echidna expects [W3C IDs for all editors](https://github.com/w3c/echidna/wiki/Preparing-your-document#data-editor-id). This is easy to add when using spec-generator; I don't know about Bikeshed.
* Echidna needs to retrieve *a WD* (not an ED) from *a public URL*; as it is now, this group would need a public instance of Bikeshed to spit out that WD for Echidna.

--
@sideshowbarker, @mikewest: ping! :)

### CODE REVIEW

**Comment by mikewest** [comment]
This looks really quite cool! Unfortunately, it's a bad time for me to really review anything; I'm out of office for the next week or so, and I will only vaguely be looking at the computer from time to time.

/cc @hillbrad who might be able to answer some of your questions in the meantime.

**Comment by tripu** [comment]
Thanks, @mikewest.
Just let us know if you need help with anything :)

**Comment by hillbrad** [comment]
This sounds great. I hope I can have an opportunity to look at it this week.  Is this safe to merge as-is, and then we can proceed with the next steps?

**Comment by tripu** [comment]
@hillbrad: yes, it's safe to merge&hellip; The only precaution before that, I'd say, is to comment out [the last line in .travis.yml](https://github.com/w3c/webappsec/pull/459/files#diff-354f30a63fb0907d4ad57269548329e3R28) (otherwise Echidna would receive an incomplete publication request every time there's a commit here, and there would be annoying messages in the mailing list).

I personally would leave this PR open until we resolve in it all the issues mentioned above; but of course it is entirely up to the people contributing to this repo, and its maintainers :¬)

**Comment by plehegar** [comment]
[[
Echidna needs to retrieve a WD (not an ED) from a public URL; as it is now, this group would need a public instance of Bikeshed to spit out that WD for Echidna.
]]

That one needs @tabatkins help since bikeshed cannot generate WDs for the moment. It can only generate EDs.

**Comment by tabatkins** [comment]
Uh, what?  Bikeshed can generate all statuses.

**Comment by plehegar** [comment]
@tabatkins I thought that there was at least on manual operation to publish a bikeshed document: auto-adjusting the external resources, remove the "../" from the url and put a copy of the stylesheet in the spec's folder for example.

**Comment by tabatkins** [comment]
Ah, ok. That's not "generating a WD", that's "generating a publication-ready folder of files, per the W3C's pub requirements". ^_^  You are correct that I don't currently auto-perform that, but I could.  I presume it should stuff everything into a zip or something?

**Comment by tripu** [comment]
@tabatkins, @hillbrad: up to you to complete what's missing in this PR to have it working (that script I mentioned), or to wait until w3c/echidna#230 is done instead.

**Comment by tabatkins** [comment]
Yeah, I'll wait for tarballs.

**Comment by tripu** [comment]
@tabatkins, Echidna understands TAR files now :)
[`labs.w3.org/echidna/api/version`](https://labs.w3.org/echidna/api/version)
[`github.com/w3c/echidna/releases/tag/v1.5.0`](https://github.com/w3c/echidna/releases/tag/v1.5.0)

(But I'm leaving this PR open for a while, in case you want to reuse some of the Travis config in it.)

**Pull request closed without merging**
