### PR TITLE
SRI: Small fixes - two typos and two link corrections

### PR DESCRIPTION
**Pull request by tagawa**

### CODE REVIEW

**Comment by mozfreddyb** [comment]
The change looks good. :+1:  Can you squash this into a single commit with a more meaningful commit message?
E.g., `git rebase -i HEAD~2` to mark the second commit as a fixup. Then `…-i HEAD~1` and pick reword to change the commit message.

Thanks!

**Comment by tagawa** [comment]
Thanks for the hint @mozfreddyb - does that look better?

**Comment by mozfreddyb** [comment]
thanks! :+1:

**Comment by tagawa** [comment]
You're welcome. And now I know how to squash commits :-)

**Pull request merged**
