### PR TITLE
Mention the one thing that integrity protects against on insecure origins

### PR DESCRIPTION
**Pull request by fmarier**
It's not strictly true that there are no security benefits at all
for including integrity metadata on an insecure page.

### CODE REVIEW

**Comment by fmarier** [comment]
@metromoxie does that wording sound good to you?

**Comment by devd** [comment]
I think instead of saying "any security whatsoever" we should say just say "Authors SHOULD deliver integrity metadata over HTTPS" and maybe reference https://w3ctag.github.io/web-https/ (since that is a broader finding and rec that we agree with)

**Comment by fmarier** [comment]
I have revised the wording following @devd's suggestion.

**Comment by devd** [comment]
minor nit, I would say "see also ..[securing the web]"

but other than that, lgtm. @metromoxie @mozfreddyb wdyt?

**Comment by fmarier** [comment]
@devd Like this? https://github.com/w3c/webappsec/pull/98/files#diff-c3b7fb78ee74e440e18502426cd8b14fR725

**Comment by devd** [comment]
yeah, this is great. lets wait for Joel/Freddy to chime in, if they want; otherwise I will merge later this week.

**Comment by mozfreddyb** [comment]
It's an important notion, to distinguish between a server compromise and an active network attacker. Thanks for taking this! :+1:

**Comment by metromoxie** [comment]
FWIW, lgtm :-)

**Pull request merged**
