### PR TITLE
Fix some typos, make a note non-redundant

### PR DESCRIPTION
**Pull request by wseltzer**
also de-whichifying

### CODE REVIEW

**Comment by wseltzer** [comment]
more typos and clarification

**Comment by mikewest** [comment]
Thanks! I'll regenerate those docs.

**Comment by mikewest** [comment]
And fix the intra-/inter- confusion. :(

Thanks!

**Comment by mikewest** [comment]
Republished the FPWD's, you should be able to grab them again. :)

**Pull request merged**
