### PR TITLE
COWL: intial commit towards FPWD

### PR DESCRIPTION
**Pull request by deian**
Thanks to @jonathanKingston for fixing a bunch of bugs in this!

### CODE REVIEW

**Comment by jonathanKingston** [comment]
@deian I can see a fair bit of difference with my bikeshed output have you updated that?

Also the generated output still has an instance of `labled` but the src file doesn't have that.

**Comment by deian** [comment]
@jonathanKingston you're right, thanks for catching that -- didn't `make COWL`

**Comment by mikewest** [comment]
Now's probably a good time to ask whether or not we want separate repositories for WebAppSec specs, or whether we'd like to keep them all in one repository (https://twitter.com/mikewest/status/639400263007236096).

/cc @hillbrad

**Comment by mikewest** [comment]
(Happy to land this either way... do you have push rights to the repository?)

**Comment by deian** [comment]
@mikewest sorry for delay. (On a boat, with periodic wiif-off periods.) I don't have push rights to the repo. Happy to keep it separate if we're going with that route. I can't tell from twritter convo if a decision was made.

**Comment by mikewest** [comment]
Started a thread at https://lists.w3.org/Archives/Public/public-webappsec/2015Sep/0039.html (and CC'd you).

**Comment by mikewest** [comment]
@wseltzer: I think the concensus is moving towards splitting the repos. Would you mind creating a COWL repository for Deian, and giving him push access, along with whoever else he'd like to help him edit the spec? I guess we could just reuse the webappsec group if you add him to it?

**Pull request merged**
