### PR TITLE
Remove note about non CORS load

### PR DESCRIPTION
**Pull request by devd**

### CODE REVIEW

**Comment by fmarier** [comment]
It seems to me like that whole section is basically trying to explain what #418 was asking about but doing a poor job at it.

We should either remove it entirely or make it useful to people who need a few more pointers about what CORS does and what attacks it prevents. My preference would be for the latter since I've had lots of questions about CORS when presenting SRI to developers.

**Comment by fmarier** [comment]
And to be clear, we're doing a poor job at this because this section predates the CORS requirement, so it was probably fine before then :)

**Comment by mozfreddyb** [comment]
Let's merge this and discuss about additional pointers in #418.

**Comment by devd** [comment]
my thinking exactly: I think this is obviously wrong so we can remove it and then make additional decisions about this section.

**Pull request merged**
