### PR TITLE
Widen scope of Permission API

### PR DESCRIPTION
**Pull request by marcoscaceres**
We are looking at expanding the scope of Permissions API to have opinions about UI, lifetimes, etc. so the text is overly restrictive.

### CODE REVIEW

**Comment by mikewest** [comment]
Exciting. Are there sketches of these plans anywhere to skim through? I'm certainly not opposed to doing more work in this area; it's important.

/cc @clelland, @engedy, and @dveditz

**Comment by marcoscaceres** [comment]
Good starting point https://github.com/w3c/geolocation-api/issues/69#issuecomment-805388266

And issue: 
https://github.com/w3c/permissions/issues/233

If we agree to widen the scope I'll start drafting up some ideas.

**Comment by clelland** [comment]
I would love to see the permissions policy features covered by this spec in some way, which could influence the text around UI and lifetimes, but I'm excited to see what comes out of this.

**Comment by marcoscaceres** [comment]
Ok, so, my rough idea is start with adding a section that broadly describes lifetimes or whatever we like. 

Then, in the [Permissions Registry](https://w3c.github.io/permissions/#permission-registry), we add something like: 

**Optional** _UI requirements_:
  - UI requirements for the given permission.

So, if there are requirements, they can be individually added for each permission as needed (same as other things in the spec). 

Then, for example, in the [Geolocation Permission](https://w3c.github.io/permissions/#geolocation) we would add something like:

> The UI requirements for the Geolocation Permission are as follows: ....  [=lifetime=] MUST something something....

**Review by VChernomYA — APPROVED** [review]

**Comment by VChernomYA** [comment]
admin/webappsec-charter-2021.html

**Pull request merged**
