### PR TITLE
it's two header fields, right?

### PR DESCRIPTION
**Pull request by dret**

### CODE REVIEW

**Comment by mikewest** [comment]
For the moment, yes. I think we're going to end up dropping the `report-only` variant, but let's merge this for now. Thanks for looking!

**Comment by dret** [comment]
good to know, thanks for commenting. i'll keep an eye out for this in the next versions. i am trying to track the evolving landscape of HTTP headers.

**Comment by mikewest** [comment]
Great. Are you summarizing the results anywhere? I'm curious. :)

**Comment by dret** [comment]
HTTP header field summary is here: https://github.com/dret/sedola/blob/master/MD/headers.md
the new draft is described here: https://github.com/dret/sedola/blob/master/W3C/csp-pinning.xml
basically, the idea is to document the "web surface" of standards and services, so that it becomes easier to describe what a consumer should understand when it wants to use a service. it's a work in progress...

**Pull request merged**
