### PR TITLE
Update examples with crossorigin=anonymous

### PR DESCRIPTION
**Pull request by devd**
For security, resources need to be CORS fetches or have public caching headers. I think it is better to have our examples use CORS fetches explicitly.

### CODE REVIEW

**Comment by mozfreddyb** [comment]
Looks good.

I think we should add a tiny ref to [https://html.spec.whatwg.org/multipage/semantics.html#attr-link-crossorigin](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-crossorigin)?

**Comment by devd** [comment]
well, two concerns: where to add it and in general, we don't add a reference for html tags/attributes, right?

**Comment by fmarier** [comment]
Given that we only support `<script>` and `<link>` elements, neither of which are prevented from loading cross-origin resources, why do we need to fetch using CORS?

**Comment by fmarier** [comment]
Or does the credential-dropping option (`anonymous`) also apply to non-CORS fetches?

**Comment by devd** [comment]
it is not actually cors fetch until we put that attribtue. So, with that attribute, teh Access-Control-Allow-Origin flag is checked and then when the right one is returned, everything works. So for anonymous, ACAO * will need to be returned. Otherwise, the CORS fetch will fail (but you can load the script without CORS; just not read it)

**Comment by mozfreddyb** [comment]
I'd hate to will break the CDN use case for JS files that do not come with an ACAO *.

This does not execute:
> `data:text/html,<script src="http://people.mozilla.org/~fbraun/files/alert.js" crossorigin=anonymous></script>`

But this here does:
>  `data:text/html,<script src="http://people.mozilla.org/~fbraun/files/alert.js"></script>`

**Comment by devd** [comment]
well, that will be caught in basic testing. The CDN only needs to send the ACAO *.

So, if you do a CORS fetch, you need to send ACAO *. This is the best solution.

Else, you don't do crossorigin=whatever fetch, and then it has to be same origin (or in the CDN case) publicly cacheable (but run time error catching might be trickier). Given that, I would rather that the spec encourages the ACAO * behavior since that is a pretty safe header to set.

**Comment by mozfreddyb** [comment]
You're completely right for big CDNs. They almost always already send ACAO *.
But for those CDNs which don't, it's hard to convince them to enable it - if you're not a paying customer.

It's even harder to include something from a library on `gh-pages`.

In essence, this means that SRI won't work for "arbitrary JS file I found on the net and want to make sure doesn't change". :-/

**Comment by annevk** [comment]
@mozfreddyb yeah, because that means violating SOP.

@devd what do you mean by public caching headers? That doesn't sound right.

**Comment by annevk** [comment]
(Violating SOP in the sense that SRI can be used to read content if you're determined or if the content is small.)

**Comment by mozfreddyb** [comment]
Well according to the *[Is resource eligible for integrity validation](http://www.w3.org/TR/SRI/#is-resource-eligible-for-integrity-validation)* algorithm, we don't need CORS to perform an integrity check. Explicitly, we need just either of these three:

> If the mode of request is CORS, return true.
> If the origin of request is resource’s origin, return true.
> If resource is [cachable by a shared cache](https://svn.tools.ietf.org/svn/wg/httpbis/draft-ietf-httpbis/latest/p6-cache.html#response.cacheability), as defined in [HTTP11], return true.

I don't think the cross-domain data can be considered sensitive, if it is publicly cachable. A "shared cache" is a proxy server, right?

NB: 
This algorithm describes the consensus we have achieved on the mailing list in the "Subresource Integrity and fingerprinting" thread (most notably [Michal Zalewski's email](https://lists.w3.org/Archives/Public/public-webappsec/2014Jan/0025.html) and @devd's [response](https://lists.w3.org/Archives/Public/public-webappsec/2014Jan/0026.html)).

**Comment by annevk** [comment]
So far we have not allowed reading intranet content when it set `Cache-Control: public`. It's not entirely clear to me why we'd start now. Sure there was that email, but what changed about SOP?

The response is also somewhat puzzling as one of the networking rules is that we treat every violation the same as a network error to not give attackers more information than strictly required.

**Comment by mozfreddyb** [comment]
Intranets ruin everything :suspect:

Seems like we have to revise that algorithm...

**Comment by mozfreddyb** [comment]
:+1: for adding `crossorigin=anonymous` to the requests then

**Comment by fmarier** [comment]
Does the fact that we don't trigger `onerror` unless the origin is the same change this reasoning at all?

In the example of an external site loading a publicly cachable intranet resource, we perform the SRI check, but we pretend everything is fine on a bad hash (while cancelling the load): https://w3c.github.io/webappsec/specs/subresourceintegrity/#the-script-element

**Comment by devd** [comment]
@annevk The idea of using public-caching was something that was decided on in the mailing lists. fwiw, I am not a fan of that and I prefer the explicit opt-in of CORS. Since Freddy has filed #207 maybe we can merge this PR? The question of whether or not to use public caching as an opt-in for SRI is something I will bring up on the list.

(please let me bring it up since right now it won't make sense until I present all the other changes we made.)

**Comment by annevk** [comment]
@devd I get that it was decided, but it is not really acceptable. This PR makes total sense though :+1:

**Comment by devd** [comment]
@fmarier what do you think about merging this? We can discuss the issues with publicly cacheable resources in #207

**Comment by mastahyeti** [comment]
> You're completely right for big CDNs. They almost always already send ACAO *.
But for those CDNs which don't, it's hard to convince them to enable it - if you're not a paying customer.

> It's even harder to include something from a library on gh-pages.

GitHub Pages now sends ACAO * for all responses :smile:.

**Comment by metromoxie** [comment]
This lgtm, although you'll need a rebase because of the changes with types/options.

**Comment by fmarier** [comment]
I've just rebased this for @devd. I think it's ready to go, but I'll let someone else double-check before merging.

**Comment by metromoxie** [comment]
Two comments:
  * Can you add "crossorigin" to the one <link> example?
  * Would you mind compiling and adding the index.html?

Otherwise lgtm.

**Comment by fmarier** [comment]
@metromoxie done

**Comment by metromoxie** [comment]
Awesome, thanks. Merging.

**Comment by devd** [comment]
awesome! thanks everyone

**Pull request merged**
