### PR TITLE
Clarify getPrioritizedHashFunction in Note

### LINKED ISSUE #387: SRI: make it clear that  getPrioritizedHashFunction() is not exposed by user agents
The current wording we have around the ` getPrioritizedHashFunction()` function is confusing to readers and has led many to believe that it will be exposed to JavaScript.

https://lists.w3.org/Archives/Public/public-webappsec/2015May/0134.html

### PR DESCRIPTION
**Pull request by devd**
Fixes #387

### CODE REVIEW

**Comment by metromoxie** [comment]
lgtm (although please run "make" before merging)

**Comment by metromoxie** [comment]
Did you mean to close without merging?

**Comment by devd** [comment]
I actually landed from command line, but it didn't auto close, so closed manually

**Comment by metromoxie** [comment]
Got it :-)

**Pull request closed without merging**
